income = float (input ("Enter your monthly income: "))
expense  = float (input ("Enter your total monthly expenses: "))
monthly_Savings = (income) - (expense)
projected_Savings = monthly_Savings * 12 + (monthly_Savings * 12 * 0.05)
print("Your monthly savings are ${:.0f}.". format(monthly_Savings))
#print(f"Projected savings after one year, with interest, is: ${Projected_Savings:g}.")
print("Projected savings after one year, with interest, is: ${:.0f}.". format(projected_Savings))
